### ISSUE TITLE
Can there be multiple autograders at once?

### ISSUE THREAD

**Issue by yo1995** [gradescope/autograder_samples#16]
For example, an instructor want to test his next autograder for the next assignment, while the current is not due yet, how should he do it?

Currently I found that when a new autograder is uploaded, the previous one got overwritten, which is not ideal since two adjacent assignments will collide with each other.

Thanks!

**Comment by ibrahima** [comment]
That should not happen; I think you also emailed help@gradescope.com about this, right? Each assignment on Gradescope has its own autograder.

The only possible exception is if you set up your own docker image and use the same image for multiple assignments, as some people have done. But otherwise if you use our autograder build setup it will generate a unique docker image name for each assignment.

Hope that helps!
